<div id="detail" class="content" style="display: none;">
    <div class="content-header mb-4">
        <h6 class="mb-0">Item Purchase Request</h6>
    </div>

    <!-- Add Detail Button -->
    <div class="row mb-4">
        <div class="col-12">
            <button type="button" class="btn btn-primary" id="addDetailBtn">
                <i class="icon-base bx bx-plus me-2"></i>Add Detail
            </button>
        </div>
    </div>

    <!-- Amount Total and Rows per page -->
    <div class="row mb-3">
        <div class="col-md-6">
            <div class="d-flex align-items-center">
                <label class="form-label me-2 mb-0">Rows per page:</label>
                <select class="form-select form-select-sm" style="width: auto;" id="rowsPerPage">
                    <option value="10" selected>10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
            </div>
        </div>
        <div class="col-md-6">
            <div class="d-flex align-items-center justify-content-end">
                <label class="form-label me-2 mb-0">Amount Total:</label>
                <input type="text" class="form-control form-control-sm text-end" id="amountTotal" value="0" disabled style="width: 150px; text-align: right;">
            </div>
        </div>
    </div>

    <!-- DataTable -->
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped table-hover" id="itemDetailTable">
                    <thead class="table-light">
                        <tr>
                            <th width="100">Action</th>
                            <th>Item ID</th>
                            <th>Item Name</th>
                            <th>Description</th>
                            <th>UoM</th>
                            <th>Currency</th>
                            <th>Qty</th>
                            <th class="text-end">Unit Price</th>
                            <th class="text-end">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Items will be dynamically added here from Add Item Detail form -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Pagination -->
    <div class="row mt-3">
        <div class="col-md-6">
            <div class="dataTables_info">
                No entries
            </div>
        </div>
        <div class="col-md-6">
            <div class="dataTables_paginate paging_simple_numbers">
                <ul class="pagination justify-content-end mb-0">
                    <!-- Pagination buttons will be dynamically generated by JavaScript -->
                </ul>
            </div>
        </div>
    </div>

    <!-- Navigation Buttons -->
    <div class="row mt-4">
        <div class="col-12 d-flex justify-content-center gap-2">
            <button class="btn btn-label-secondary btn-prev">
                <i class="icon-base bx bx-left-arrow-alt scaleX-n1-rtl icon-sm ms-sm-n2 me-sm-2"></i>
                <span class="align-middle d-sm-inline-block d-none">Back</span>
            </button>
            <button class="btn btn-success" id="saveDraftBtn">
                <i class="icon-base bx bx-save me-2"></i>
                <span class="align-middle d-sm-inline-block d-none">Save Draft</span>
            </button>
            <button class="btn btn-outline-dark btn-next">
                <span class="align-middle d-sm-inline-block d-none me-sm-2">Continue</span>
                <i class="icon-base bx bx-right-arrow-alt scaleX-n1-rtl icon-sm me-sm-n2"></i>
            </button>
        </div>
    </div>

    <!-- Include Add Item Detail Partial -->
    @include('procurement.purchase_request.create.partials._AddItemDetailPartial')
</div>
