<div id="document" class="content" style="display: none;">
    <div class="content-header mb-4">
        <h6 class="mb-0">Supporting Document</h6>
        <small>Manage and upload supporting documents for your procurement request.</small>
    </div>

    <!-- Add Document Button and Rows per page -->
    <div class="row mb-3">
        <div class="col-md-6">
            <div class="d-flex align-items-center">
                <label class="form-label me-2 mb-0">Rows per page:</label>
                <select class="form-select form-select-sm" style="width: auto;" id="documentRowsPerPage">
                    <option value="10" selected>10</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
            </div>
        </div>
        <div class="col-md-6">
            <div class="d-flex align-items-center justify-content-end">
                <button type="button" class="btn btn-primary" id="addDocumentBtn">
                    <i class="icon-base bx bx-plus me-2"></i>Add Document
                </button>
            </div>
        </div>
    </div>

    <!-- DataTable -->
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-striped table-hover" id="documentTable">
                    <thead class="table-light">
                        <tr>
                            <th width="80">Action</th>
                            <th>File Name</th>
                            <th>File Size (kb)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Documents will be dynamically added here from file upload -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Pagination -->
    <div class="row mt-3">
        <div class="col-md-6">
            <div class="dataTables_info">
                No entries
            </div>
        </div>
        <div class="col-md-6">
            <div class="dataTables_paginate paging_simple_numbers">
                <ul class="pagination justify-content-end mb-0">
                    <!-- Pagination buttons will be dynamically generated by JavaScript -->
                </ul>
            </div>
        </div>
    </div>

    <!-- Navigation Buttons -->
    <div class="row mt-4">
        <div class="col-12 d-flex justify-content-center gap-2">
            <button class="btn btn-label-secondary btn-prev">
                <i class="icon-base bx bx-left-arrow-alt scaleX-n1-rtl icon-sm ms-sm-n2 me-sm-2"></i>
                <span class="align-middle d-sm-inline-block d-none">Back</span>
            </button>
            <button class="btn btn-success" id="saveDraftDocumentBtn">
                <i class="icon-base bx bx-save me-2"></i>
                <span class="align-middle d-sm-inline-block d-none">Save Draft</span>
            </button>
            <button class="btn btn-outline-dark btn-next">
                <span class="align-middle d-sm-inline-block d-none me-sm-2">Continue</span>
                <i class="icon-base bx bx-right-arrow-alt scaleX-n1-rtl icon-sm me-sm-n2"></i>
            </button>
        </div>
    </div>
</div>
